### ISSUE TITLE
Epic: Partial Tracing

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa-lab/squeak-tracedebugger#106]
- [ ] toggle all kinds of tracing (state + behavior) through a button in the bar
- [ ] toggle just state tracing through a button?
- [ ] #39 
- [ ] opt-in to tracing certain primitives (BitBlt)?
- [ ] presets for excluded methods?

For the UI: Ideally, add a stateful menu button "Tracing" to the main button bar and provide the other options in the menu.
